AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline stack for deploying portfolio website from GitHub to S3

Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket where the website is deployed

Resources:
  # IAM Role for CodePipeline
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # S3 Bucket for CodePipeline Artifacts
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-artifacts-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain  # Keep the bucket after the stack is deleted

  # IAM Role for CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # CodeBuild Project to Build and Deploy the Portfolio to S3
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-build"
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !Ref S3BucketName
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${!Sub '{{resolve:secretsmanager:gitOAuth:SecretString:GitHubRepository}}'}.git"
        GitCloneDepth: 1
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      TimeoutInMinutes: 10

  # CodePipeline for Continuous Deployment from GitHub to S3
  PortfolioCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Sub "{{resolve:secretsmanager:gitOAuth:SecretString:GitHubRepository}}"
                Branch: !Sub "{{resolve:secretsmanager:gitOAuth:SecretString:GitHubBranch}}"
                OAuthToken: !Sub "{{resolve:secretsmanager:gitOAuth:SecretString:GitHubToken}}"
                Owner: !Sub "{{resolve:secretsmanager:gitOAuth:SecretString:GitHubUsername}}"
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject

Outputs:
  CodePipelineName:
    Description: The name of the CodePipeline
    Value: !Ref PortfolioCodePipeline
    Export:
      Name: !Sub "${AWS::StackName}-CodePipelineName"
