AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket stack for static website hosting

Parameters:
  DomainName:
    Type: String
    Description: The domain name for the website (e.g., example.com)
    Default: "longltt-portfolio.com"

Resources:
  # S3 Bucket for Static Website Hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-website-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    DeletionPolicy: Retain  # Retain bucket when stack is deleted

  # S3 Bucket Policy to Allow Public Access
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

Outputs:
  # Export the S3 Bucket Name for other stacks to use
  WebsiteBucketName:
    Description: The name of the S3 bucket hosting the website
    Value: !Ref WebsiteBucket
    Export:
      Name: "S3BucketName"  # Make sure this export name is correct and consistent
